#lang racket
(define (faction)
  (define (printw num w)
    (if (> num w)
        (void)
        (begin (display num) (display #\,)(printw (+ num 1) w))))
  (define (printline r w)
    (if (= r 0)
        (void)
        (begin (printw 1 w)(newline)(printline (- r 1) w))))
  (let ((r (read))
        (w (read)))
    (if (eq? r eof)
        (void)
        (printline r w))))