#lang racket
(define (carorcdr n x res)
  (if (= (remainder n x) 0)
      (carorcdr (/ n x) x (+ res 1))
      res))
(define (car n)
  (carorcdr n 2 0))
(define (cdr n)
  (carorcdr n 3 0))

(define (fast-exp a n)
  (define (square x) (* x x))
  (define (iter a n result)
    (if (= n 0)
        result
        (if (even? n)
            (iter (square a) (/ n 2) result)
            (iter (square a) (/ (- n 1) 2) (* a result)))))
  (iter a n 1))

(define (cons a b)
  (* (fast-exp 2 a ) (fast-exp 3 b)))

(define (myloop)
  (let ((a (read))
        (b (read)))
    (if (eq? a eof)
        (void)
        (begin (display (car (cons a b)))
               (display " ")
               (display (cdr (cons a b)))
               (newline)
               (myloop)))))
(myloop)